- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Check MySQL status
  command: systemctl status mysql
  register: mysql_status
  failed_when: mysql_status.rc != 0
  become: yes

- name: Set up MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: "localhost"
    state: present
  become: yes
